### ISSUE TITLE
RuntimeError: Encoding 'SequentialGrid' not found

### ISSUE THREAD

**Issue by tb2-sy** [hturki/suds#15]
Traceback (most recent call last):
  File "XX/XXX/suds/suds/train.py", line 113, in <module>
    suds_entrypoint()
  File "XX/XXX/suds/suds/train.py", line 104, in suds_entrypoint
    main(
  File "XX/XXX/Anacondas/anaconda3/envs/suds/lib/python3.9/site-packages/scripts/tr
ain.py", line 233, in main
    launch(
  File "XX/XXX/Anacondas/anaconda3/envs/suds/lib/python3.9/site-packages/scripts/tr
ain.py", line 172, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "XX/XXX/Anacondas/anaconda3/envs/suds/lib/python3.9/site-packages/scripts/tr
ain.py", line 86, in train_loop
    trainer.setup()
  File "XX/XXX/Anacondas/anaconda3/envs/suds/lib/python3.9/site-packages/nerfstudio
/engine/trainer.py", line 141, in setup
    self.pipeline = self.config.pipeline.setup(
  File "XX/XXX/Anacondas/anaconda3/envs/suds/lib/python3.9/site-packages/nerfstudio
/configs/base_config.py", line 57, in setup
    return self._target(self, **kwargs)
  File "XX/XXX/suds/suds/data/suds_pipeline.py", line 65, in __init__ super().__init__(config, device, test_mode, world_size, local_rank)
  File "XX/XXX/Anacondas/anaconda3/envs/suds/lib/python3.9/site-packages/nerfstudio
/pipelines/base_pipeline.py", line 236, in __init__
    self._model = config.model.setup(
  File "XX/XXX/Anacondas/anaconda3/envs/suds/lib/python3.9/site-packages/nerfstudio
/configs/base_config.py", line 57, in setup
    return self._target(self, **kwargs)
  File "XX/XXX/suds/suds/suds_model.py", line 350, in __init__
    self.dynamic = DynamicField(
  File "XX/XXX/suds/suds/fields/dynamic_field.py", line 48, in __init__
    self.encoding = tcnn.Encoding(
  File "XX/XXX/Anacondas/anaconda3/envs/suds/lib/python3.9/site-packages/tinycudann
-1.7-py3.9-linux-x86_64.egg/tinycudann/modules.py", line 315, in __init__
    super(Encoding, self).__init__(seed=seed)
  File "XX/XXX/Anacondas/anaconda3/envs/suds/lib/python3.9/site-packages/tinycudann
-1.7-py3.9-linux-x86_64.egg/tinycudann/modules.py", line 157, in __init__
    self.native_tcnn_module = self._native_tcnn_module()
  File "XX/XXX/Anacondas/anaconda3/envs/suds/lib/python3.9/site-packages/tinycudann
-1.7-py3.9-linux-x86_64.egg/tinycudann/modules.py", line 320, in _native_tcnn_module
    return _C.create_encoding(self.n_input_dims, self.encoding_config, self.precision)
    RuntimeError: Encoding 'SequentialGrid' not found
    --------------------------------------------------------------------------------
When I run python suds/train.py suds --experiment-name $EXPERIMENT_NAME --pipeline.datamanager.dataparser.metadata_path $METADATA_PATH [--pipeline.feature_clusters $FEATURE_CLUSTERS], the following error is reported, this problem has been troubled I'm at this for days and I suspect it's a tiny-cuda-nn problem. But I didn't see a similar problem in the issue in tiny-cuda-nn......

**Comment by vermouth599** [comment]
I met the same issue, could you please tell me how to solve this?
