### ISSUE TITLE
How do you eval your model?

### ISSUE THREAD

**Issue by Quantum-matrix** [hturki/suds#20]
Thanks for your great work!
It seems what is given in the readme is not right. 
`python suds/eval.py --load_config $SAVED_MODEL_PATH`
First, the model path is not a config. Second, I just see the config for training and when I use that config, it turns out:
`Traceback (most recent call last):
  File "/root/autodl-tmp/suds/suds/eval.py", line 102, in <module>
    entrypoint()
  File "/root/autodl-tmp/suds/suds/eval.py", line 98, in entrypoint
    tyro.cli(ComputePSNR).main()
  File "/root/autodl-tmp/suds/suds/eval.py", line 34, in main
    config, pipeline, checkpoint_path = eval_setup(self.load_config)
  File "/root/miniconda3/envs/suds/lib/python3.9/site-packages/nerfstudio/utils/eval_utils.py", line 88, in eval_setup
    assert isinstance(config, TrainerConfig)
AssertionError`

**Comment by hturki** [comment]
just to confirm, are you pointing towards the config.yml file in the saved model path directory?
