### ISSUE TITLE
RuntimeError: Encoding 'SequentialGrid' not found

### ISSUE THREAD

**Issue by vermouth599** [hturki/suds#36]
Traceback (most recent call last):
  File "/root/autodl-tmp/suds/suds/train.py", line 111, in <module>
    suds_entrypoint()
  File "/root/autodl-tmp/suds/suds/train.py", line 102, in suds_entrypoint
    main(
  File "/root/miniconda3/envs/suds/lib/python3.9/site-packages/scripts/train.py", line 233, in main
    launch(
  File "/root/miniconda3/envs/suds/lib/python3.9/site-packages/scripts/train.py", line 172, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/root/miniconda3/envs/suds/lib/python3.9/site-packages/scripts/train.py", line 86, in train_loop
    trainer.setup()
  File "/root/miniconda3/envs/suds/lib/python3.9/site-packages/nerfstudio/engine/trainer.py", line 141, in setup
    self.pipeline = self.config.pipeline.setup(
  File "/root/miniconda3/envs/suds/lib/python3.9/site-packages/nerfstudio/configs/base_config.py", line 57, in setup
    return self._target(self, **kwargs)
  File "/root/autodl-tmp/suds/suds/data/suds_pipeline.py", line 65, in __init__
    super().__init__(config, device, test_mode, world_size, local_rank)
  File "/root/miniconda3/envs/suds/lib/python3.9/site-packages/nerfstudio/pipelines/base_pipeline.py", line 236, in __init__
    self._model = config.model.setup(
  File "/root/miniconda3/envs/suds/lib/python3.9/site-packages/nerfstudio/configs/base_config.py", line 57, in setup
    return self._target(self, **kwargs)
  File "/root/autodl-tmp/suds/suds/suds_model.py", line 350, in __init__
    self.dynamic = DynamicField(
  File "/root/autodl-tmp/suds/suds/fields/dynamic_field.py", line 48, in __init__
    self.encoding = tcnn.Encoding(
  File "/root/miniconda3/envs/suds/lib/python3.9/site-packages/tinycudann-1.7-py3.9-linux-x86_64.egg/tinycudann/modules.py", line 315, in __init__
    super(Encoding, self).__init__(seed=seed)
  File "/root/miniconda3/envs/suds/lib/python3.9/site-packages/tinycudann-1.7-py3.9-linux-x86_64.egg/tinycudann/modules.py", line 157, in __init__
    self.native_tcnn_module = self._native_tcnn_module()
  File "/root/miniconda3/envs/suds/lib/python3.9/site-packages/tinycudann-1.7-py3.9-linux-x86_64.egg/tinycudann/modules.py", line 320, in _native_tcnn_module
    return _C.create_encoding(self.n_input_dims, self.encoding_config, self.precision)
RuntimeError: Encoding 'SequentialGrid' not found

**Comment by vermouth599** [comment]
-> None:
        super().__init__()

        self.geo_feat_dim = geo_feat_dim
        self.feature_output_activation = feature_output_activation

        self.encoding = tcnn.Encoding(
            n_input_dims=5,
            encoding_config={
                'otype': 'SequentialGrid',
                'n_levels': num_levels,
                'n_features_per_level': features_per_level,
                'log2_hashmap_size': log2_hashmap_size,
                'base_resolution': base_resolution,
                'include_static': False
            }
        )
Where can I find this "SequentialGrid"?

**Comment by fferroni** [comment]
I suspect you need to have the tinycuda and NerfStudio branches defined in the conda dependencies. It’s not a standard version.

**Comment by vermouth599** [comment]
> I suspect you need to have the tinycuda and NerfStudio branches defined in the conda dependencies. It’s not a standard version.

Thank you very much！Now the problem is solved.

**Comment by baekhyun77** [comment]
i also have this question,could you please tell me how to solve this?
