### ISSUE TITLE
"RuntimeError: CUDA error: device-side assert triggered CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect."

### ISSUE THREAD

**Issue by rockywind** [hturki/suds#5]
Hi,
Thank you for sharing the great work.
I met the error below when I ran the script `CUDA_VISIBLE_DEVICES=1,3 python -m torch.distributed.run --standalone --nnodes=1 --nproc_per_node 2 scripts/extract_dino_correspondences.py --metadata_path metadata/kitti-06.json #for multi-GPU extraction
`
The error is below.
````
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Using cache found in /root/.cache/torch/hub/facebookresearch_dino_main
Using cache found in /root/.cache/torch/hub/facebookresearch_dino_main
  0%|            |scripts/extract_dino_correspondences.py:86: ConvergenceWarning: Number of distinct clusters (6265) found smaller than n_clusters (6269). Possibly due to duplicate points in X.
  kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10).fit(normalized)
../aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [12,0,0], thread: [106,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [12,0,0], thread: [113,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [12,0,0], thread: [121,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [12,0,0], thread: [124,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
  0%|          | 0/270 [1:17:49<?, ?it/s]
Traceback (most recent call last):
  File "scripts/extract_dino_correspondences.py", line 230, in <module>
    main(_get_opts())
  File "/opt/conda/envs/suds_my/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "scripts/extract_dino_correspondences.py", line 212, in main
    points1, points2, image1_pil, image2_pil = find_correspondences(extractor, first, second,
  File "scripts/extract_dino_correspondences.py", line 108, in find_correspondences
    img1_y_to_show = (img1_indices_to_show / num_patches1[1]).cpu().numpy()
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 292460 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 292459) of binary: /opt/conda/envs/suds_my/bin/python
Traceback (most recent call last):
  File "/opt/conda/envs/suds_my/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/suds_my/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/suds_my/lib/python3.8/site-packages/torch/distributed/run.py", line 765, in <module>
    main()
  File "/opt/conda/envs/suds_my/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/envs/suds_my/lib/python3.8/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/opt/conda/envs/suds_my/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/opt/conda/envs/suds_my/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/envs/suds_my/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=======================================================
scripts/extract_dino_correspondences.py FAILED
-------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-04-01_13:51:34
  host      : bl5a0rj6b5t0e-0
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 292459)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 292459
=======================================================
````

**Comment by rockywind** [comment]
Hi,
Another issue is Why does run_pca take six hours and still not finish?
This is the script `python scripts/run_pca.py --metadata_path metadata/kitti-06.json`.
![image](https://user-images.githubusercontent.com/14838781/229295086-c2f00f69-50a6-4341-92c8-69623d01c38f.png)

**Comment by hturki** [comment]
Hey, not sure about your data I think this line is suspect:

  0%|            |scripts/extract_dino_correspondences.py:86: ConvergenceWarning: Number of distinct clusters (6265) found smaller than n_clusters (6269). Possibly due to duplicate points in X.

As a heads up, it will be a while before I can dig into this deeper myself - have some deadlines in the next few weeks and afterwards I'll be OOTO until about end of May. The dino extraction code is mainly taken from https://github.com/ShirAmir/dino-vit-features so looking at that repo might also be helpful
